"""create bookings table

Revision ID: 5ff4507e8b53
Revises: b3ee5ae20e25
Create Date: 2024-03-13 23:00:37.439914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff4507e8b53'
down_revision = 'b3ee5ae20e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('consumer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consumer_id'], ['users.id'], name=op.f('fk_bookings_consumer_id_users')),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name=op.f('fk_bookings_provider_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###
