"""add status column to bookings table

Revision ID: 843e16168626
Revises: 679e16631cd5
Create Date: 2024-03-16 19:26:34.246531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843e16168626'
down_revision = '679e16631cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
