"""add status column to bookings table

Revision ID: d0a8231cf9e5
Revises: 843e16168626
Create Date: 2024-03-16 19:48:28.874639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a8231cf9e5'
down_revision = '843e16168626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_bookings')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.create_table('_alembic_tmp_bookings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(), nullable=False),
    sa.Column('time', sa.VARCHAR(), nullable=False),
    sa.Column('provider_id', sa.INTEGER(), nullable=True),
    sa.Column('consumer_id', sa.INTEGER(), nullable=True),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['consumer_id'], ['users.id'], name='fk_bookings_consumer_id_users'),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name='fk_bookings_provider_id_users'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='fk_bookings_service_id_services'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
